const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { FFMPEG_TIMEOUT_MS, STORY_MAX_SECONDS } = require('./videoProcessing');

const source = fs.readFileSync(path.join(__dirname, 'videoProcessing.js'), 'utf8');
const postController = fs.readFileSync(path.join(__dirname, '../controllers/postController.js'), 'utf8');
assert.equal(STORY_MAX_SECONDS, 30);
assert.ok(FFMPEG_TIMEOUT_MS > 0 && FFMPEG_TIMEOUT_MS <= 120_000);
assert.match(source, /MAX_FFMPEG_STDERR_BYTES/);
assert.match(source, /child\.kill\('SIGKILL'\)/);
assert.match(source, /'-nostdin'/);
assert.match(source, /'-threads', '2'/);
const storyProcessing = source.slice(source.indexOf('const processStoryVideo'), source.indexOf('// Post videos'));
assert.match(storyProcessing, /validateVideoFile\(inputPath\)/);
assert.match(storyProcessing, /validateVideoFile\(outputPath/);
assert.doesNotMatch(storyProcessing, /return file/);
const postFastStart = source.slice(source.indexOf('const processPostVideo'), source.indexOf('module.exports'));
assert.match(postFastStart, /'-c', 'copy'/);
assert.match(postFastStart, /'-movflags', '\+faststart'/);
assert.match(postFastStart, /validateVideoFile\(inputPath\)/);
assert.match(postFastStart, /validateVideoFile\(outputPath, \{ expectedDuration: sourceMetadata\.duration \}\)/);
assert.match(postFastStart, /'-xerror'/);
assert.match(source, /runPacketIntegrityScan/);
assert.match(source, /runDecodeSample/);
assert.match(postFastStart, /throw mediaIntegrityError/);
assert.doesNotMatch(postFastStart, /uploading original MP4 video/);
assert.match(source, /stream=index,codec_type,codec_name,width,height,duration,bit_rate/);
assert.match(postFastStart, /startsWith\('video\/'\)/);
assert.match(postController, /processPostVideo\(\{/);
assert.match(postController, /integrityContext/);
assert.match(postController, /uploadMultipleFiles\(startupOptimizedMedia, 'gaming-social\/posts'\)/);

console.log('Video processing resource-bound contracts passed');
